services:
  db2:
    image: icr.io/db2_community/db2:11.5.8.0
#    restart: always
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: false
      REPODB: false
      IS_OSXFS: true
      PERSISTENT_HOME: false
      HADR_ENABLED: false
      ETCD_ENDPOINT:
      ETCD_USERNAME:
      ETCD_PASSWORD:
    ports:
      - "50000:50000"                  # DB2のデフォルトポート
    volumes:
       - ./database:/database             # 永続化するためのボリューム
    platform: linux/x86_64
    command: ["bash", "/database/init_scripts/init.sh"]
