services:

  ui:
    image: node:20.16.0-alpine
    volumes:
      - ../chat-ui:/app
    ports:
      - "3000:3000"
    environment:
      API_HOST: "api"
      CHOKIDAR_USEPOLLING: true # hot reload
    command:
      sh -c "cd /app && npm install && npm run dev"
    depends_on:
      api:
        condition: service_healthy

  api:
    image: gradle:8.8-jdk21-alpine
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "db"
      DB_DATABASE: "chat"
    volumes:
      - ../chat-api:/app
    depends_on:
      db:
        condition: service_healthy
    command:
      sh -c "cd /app && gradle bootJar && java -jar /app/build/libs/chat-api.jar"
    healthcheck:
      test: sh -c "apk add curl && curl -f http://localhost:8080/chatrooms"
      start_period: 10s
      interval: 3s
      timeout: 10s
      retries: 20

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat_owner
      POSTGRES_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      start_period: 10s
      interval: 3s
      retries: 10
      timeout: 10s

